src/InformationSystemMVC/InformationSystemInfrastructure/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InformationSystemDomain.Model;
using InformationSystemInfrastructure;
using InformationSystemInfrastructure.Services;

namespace InformationSystemInfrastructure.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly ProjectCsContext _context;

        public SubjectsController(ProjectCsContext context)
        {
            _context = context;
        }

        // GET: Subjects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Subjects.ToListAsync());
        }

        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .FirstOrDefaultAsync(m => m.SubjectId == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // GET: Subjects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SubjectId,Description,Name")] Subject subject)
        {
            var existingPublication = await _context.Subjects
                 .Where(u => EF.Functions.Like(u.Name, subject.Name))
                 .FirstOrDefaultAsync();

            if (existingPublication != null)
            {
                ModelState.AddModelError("Name", "Subject with the same name already exists.");
            }
            if (ModelState.IsValid)
            {
                _context.Add(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SubjectId,Description,Name")] Subject subject)
        {
            if (id != subject.SubjectId)
            {
                return NotFound();
            }

            var existingPublication = await _context.Subjects
                 .Where(u => EF.Functions.Like(u.Name, subject.Name))
                 .FirstOrDefaultAsync();

            if (existingPublication != null)
            {
                ModelState.AddModelError("Name", "Subject with the same name already exists.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.SubjectId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var subject = await _context.Subjects
                .FirstOrDefaultAsync(m => m.SubjectId == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //Cascade test
            var relatedarticles = await _context.Subjects
                .Include(s => s.Articles)
                    .ThenInclude(a => a.Comments)
                .Include(s => s.Articles)
                    .ThenInclude(a => a.AuthorsPerArticles)
                .FirstOrDefaultAsync(s => s.SubjectId == id);
            if (relatedarticles != null)
            {
                foreach (var article in relatedarticles.Articles)
                {
                    _context.Comments.RemoveRange(article.Comments);
                    _context.AuthorsPerArticles.RemoveRange(article.AuthorsPerArticles);
                }
                _context.Articles.RemoveRange(relatedarticles.Articles);
            }
            //
            var subject = await _context.Subjects.FindAsync(id);
            if (subject != null)
            {
                _context.Subjects.Remove(subject);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectExists(int id)
        {
            return _context.Subjects.Any(e => e.SubjectId == id);
        }
        [HttpGet]
        public IActionResult Import()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile fileExcel, CancellationToken cancellationToken = default)
        {
            var importService = new SubjectDataPortServiceFactory(_context).GetImportService(fileExcel.ContentType);
            using var stream = fileExcel.OpenReadStream();
            await importService.ImportFromStreamAsync(stream, cancellationToken);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Export([FromQuery] string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        CancellationToken cancellationToken = default)
        {
            var exportService = new SubjectDataPortServiceFactory(_context).GetExportService(contentType);

            var memoryStream = new MemoryStream();

            await exportService.WriteToAsync(memoryStream, cancellationToken);

            await memoryStream.FlushAsync(cancellationToken);
            memoryStream.Position = 0;


            return new FileStreamResult(memoryStream, contentType)
            {
                FileDownloadName = $"categiries_{DateTime.UtcNow.ToShortDateString()}.xlsx"
            };
        }
        }
    }

src/InformationSystemMVC/InformationSystemInfrastructure/Views/Subjects/Create.cshtml
@model InformationSystemDomain.Model.Subject

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Subject</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="button2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="button2" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/InformationSystemMVC/InformationSystemInfrastructure/Views/Subjects/Delete.cshtml
@model InformationSystemDomain.Model.Subject

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Subject</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SubjectId" />
        <input type="submit" value="Delete" class="button-delete1" />
        <a class="button2" asp-action="Index">Back to List</a>
    </form>
</div>

src/InformationSystemMVC/InformationSystemInfrastructure/Views/Subjects/Details.cshtml
@model InformationSystemDomain.Model.Subject

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Subject</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        
    </dl>
</div>
<div>
    <a class="button2" asp-action="Edit" asp-route-id="@Model?.SubjectId">Edit</a> 
    <a class ="button2" asp-action="Index">Back to List</a>
</div>

src/InformationSystemMVC/InformationSystemInfrastructure/Views/Subjects/Edit.cshtml
@model InformationSystemDomain.Model.Subject

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Subject</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SubjectId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="button2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="button2" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/InformationSystemMVC/InformationSystemInfrastructure/Views/Subjects/Import.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Import</h1>


<div>
    <h3>Оберіть excel-файл для завантаження</h3>
    @using (Html.BeginForm("Import", "Subjects", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
    {
        <div>
            Завантажте Excel-файл:
            <input type="file" name="fileExcel" id="fileExcel" />
            <div>
                <input type="submit" value="Завантажити" />
            </div>
        </div>
    }
    <a class="button2" asp-action="Index">Back</a>
</div>

src/InformationSystemMVC/InformationSystemInfrastructure/Views/Subjects/Index.cshtml
@model IEnumerable<InformationSystemDomain.Model.Subject>

@{
    ViewData["Title"] = "Subjects";
}

<h1>Subjects</h1>

<p>
    <a class ="button2" asp-action="Create">Create New</a>
</p>
<p>
    <a class="button2" type="submit" asp-area="" asp-controller="Subjects" asp-action="Import">Import</a>
</p>
<p>
    <a class="button2" type="submit" asp-area="" asp-controller="Subjects" asp-action="Export">Export</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            
            <td>
                <a class="button2"  asp-action="Edit" asp-route-id="@item.SubjectId">Edit</a>
                <a class="button2" asp-action="Details" asp-route-id="@item.SubjectId">Details</a>
                <a class="button2" asp-action="Delete" asp-route-id="@item.SubjectId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>